# Generated by Django 2.1 on 2018-09-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gouwuche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnum', models.CharField(max_length=10)),
                ('go1', models.CharField(max_length=50)),
                ('go2', models.CharField(max_length=50)),
                ('go3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shangping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('speck', models.TextField()),
                ('img', models.CharField(max_length=80)),
                ('manage', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Yonghu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=8)),
                ('shouhuo', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=8)),
                ('passwordd', models.CharField(max_length=50)),
            ],
        ),
    ]
