# Generated by Django 2.1 on 2018-09-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jindong', '0002_auto_20180921_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guanliyuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=8)),
                ('phone', models.CharField(max_length=50)),
                ('passwordd', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='password',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='passwordd',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='sex',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='shouhuo',
            field=models.CharField(max_length=80),
        ),
    ]
