# Generated by Django 2.1 on 2018-09-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jindong', '0003_auto_20180926_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yonghu',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
